services:
  db:
    image: postgres:17
    container_name: db
    
    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_vol:/var/lib/postgresql/data
      - ./init.d/initdb.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_vol:
