services:
#--------------------- APP
  app:
    build: .
    image: my-test-dkfile

    ports:
      - "8080:8080"

    env_file:
      - .env

    volumes:
      - vol_app:/app

    depends_on:
      db:
        condition: service_healthy

    networks:
      - app_network

    restart: unless-stopped

#--------------------- DB
  db:
    image: postgres:17
    container_name: db
    
    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_vol:/var/lib/postgresql/data
      - ../init.d/initdb.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - app_network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

#--------------------- OTHER
volumes:
  postgres_vol:
  vol_app:

networks:
  app_network:
